# tools/Makefile
# Created 2025-11-16 by Kurt M. Weber
# This file is part of CosmOS, a component of the Cosmoverse
# Licensed under Hippocratic License with clauses:
# HL3-CL-ECO-EXTR-FFD-MEDIA-MY-SUP-SV-TAL-USTA-XUAR
# See file LICENSE for full licensing information.

.PHONY: all clean

all: 3rdparty

3rdparty:
	cd 3rdparty && make


clean: 3rdparty-clean

3rdparty-clean:
	cd 3rdparty && make clean